---
kind: pipeline
type: docker
name: lint

steps:
- name: salt-lint
  image: warpnetbv/salt-lint
  commands:
  - find . -not -path "./formulas/*" -name "*.sls" | xargs salt-lint -x 204

---
kind: pipeline
type: docker
name: push

steps:
- name: webhook
  image: plugins/webhook
  settings:
    urls: http://salt.whyrl.fr:9000/hooks/salt-drone-deployment
    content_type: application/json
    headers:
      from_secret: webhook_header
    debug: true

depends_on:
- lint

---
kind: pipeline
name: after
type: docker

steps:
- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook

depends_on:
- push
